image: "gitpod/workspace-full"

tasks:
  - name: "Install dependencies"
    before: |
      curl -L https://foundry.paradigm.xyz | bash
      source ~/.bashrc
      foundryup
      npm install -g pnpm
    init: "pnpm install"

vscode:
  extensions:
    - "esbenp.prettier-vscode"
    - "NomicFoundation.hardhat-solidity"
