# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
src = "src"
out = "out"
libs = ["lib", "../node_modules"]
solc = "0.8.25" # Pin specific version for reproducibility
optimizer = true
optimizer_runs = 200
fuzz = { runs = 256 }              # Reduced for faster normal runs
invariant = { runs = 10, depth = 15, fail_on_revert = false } # Keep false for now to match current behavior
gas_reports = ["*"]               # Generate gas reports for all contracts
script = "script"
test = "test"
auto_detect_solc = false
block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
bytecode_hash = "none"
evm_version = "cancun"
fs_permissions = [{ access = "read-write", path = "./deployments"}, { access = "read", path = "./"}]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[profile.thorough]
# Deep testing profile for comprehensive coverage
fuzz = { runs = 1000 }
invariant = { runs = 100, depth = 50, fail_on_revert = false }
verbosity = 2

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[etherscan]
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
  optimism_sepolia = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }

[rpc_endpoints]
  localhost = "http://localhost:8545"
  mainnet = "https://mainnet.infura.io/v3/${API_KEY_INFURA}"
  sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
  optimism = "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}"
  optimism_sepolia = "https://optimism-sepolia.infura.io/v3/${API_KEY_INFURA}"
